### ISSUE TITLE
Testing: Exclude column from sort by

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/FacetedBrowse#23]
In an effort to address #22, the `exclude-sort-by` branch adds the ability to exclude a column from the sorting drop-down list on the public interface.

To test this, you'll need to checkout the `exclude-sort-by` branch and upgrade the module. I'll assume you already have a faceted browse page configured and assigned to your site navigation. If not, go ahead and do that. Go to Site > Faceted browse > Page > Category and edit a column. In the sidebar, Under "Column name," you should see a new "Exclude sort by" checkbox. Check this, click on "Set column," and save the category. Now go to the public interface and see if the column is excluded from the sorting drop-down list. Then, in the admin interface, try un-checking the "Exclude sort by" checkbox and see if it's included in the public sorting drop-down list.

**Comment by jbhistorian** [comment]
Jim, thank you for the new version of the module. I tested the new version on this page: https://records.njslavery.org/s/doc/faceted-browse/1
I was able to successfully exclude two columns from sort.

I noticed some strange behavior that wasn't happening before. Selecting a value radio button makes that value jump to the top of the list. I'm not sure if this is expected behavior (the list would remain static on the page in the previous version of the module). Here's a screen capture showing what I'm talking about:
https://capture.dropbox.com/Ik9Z0P0yjQdBXPPo

**Comment by katknow** [comment]
I'm getting this error when I try to add a new column: 
Notice: Undefined index: o-module-faceted_browse:exclude_sort_by in /var/www/html/katknow/OmekaSTesting/modules/FacetedBrowse/view/faceted-browse/site-admin/category/column-row.phtml on line 35

**Comment by jimsafley** [comment]
@jbhistorian Thank you for testing. To be clear, the changes are on a branch and in testing. They are not released and not ready for production use.

As for the "jump to the top" behavior you're seeing. That's expected and necessary due to list truncation. It follows established patterns in most faceted search interfaces. Perhaps you upgraded from an early version of the module?

**Comment by katknow** [comment]
This is working as described.
