### ISSUE TITLE
Documentation: truncate more select lists

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/FacetedBrowse#34]
See [the testing issue](https://github.com/omeka-s-modules/FacetedBrowse/issues/32).

**Comment by allanaaa** [comment]
Is this expected behaviour? That a "resource with ID" and "Add all available values" would display with the IDs in the admin side, but without IDs on the public side?

<img width="330" alt="Screenshot 2023-11-30 at 15 13 44" src="https://github.com/omeka-s-modules/FacetedBrowse/assets/28012148/544ec98d-98f7-493e-868c-40b54acc79d9">
<img width="482" alt="Screenshot 2023-11-30 at 15 14 19" src="https://github.com/omeka-s-modules/FacetedBrowse/assets/28012148/cda775f7-3b97-462a-bd7e-39f5c1e6ac10">

**Comment by jimsafley** [comment]
That is expected.
