### ISSUE TITLE
Testing: New "User text" field for categories

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/FacetedBrowse#45]
The [category-user-text](https://github.com/omeka-s-modules/FacetedBrowse/compare/main...category-user-text) branch adds the "User text" field to the category form. This field allows page builders to add short instructions, a link to instructions, etc. to the public-facing category sidebar, above the facets. (See #29.)

To test this, check out the "category-user-text" branch, upgrade the module, and edit any category. You should see the new "User text" field where you can add HTML. Add some HTML and save the form. Go to the category on the public interface. You should see a "View info" button that expands the text. After expanded, you should see a "Collapse info" button that collapses the text.

**Comment by jimsafley** [comment]
I considered this very thing. My thought process was that users wouldn't want the info to push the facets below the fold, so I put it in a collapsed div.

**Comment by kimisgold** [comment]
I agree that I would rather the user text appear by default. Once it's collapsed, it takes up very little vertical space, and the collapsed state persists throughout interactions with the faceted browse. My additional suggestion would be to make the label for the expand-collapse toggle a configurable setting, like "User text label". I've simplified it to "Instructions" for the time being: that way we don't have to manage changing labels like "View [x] / "Hide [x]". The arrow icon state should be intuitive enough for most users, while the pattern from the core alerts screen readers of the button's expanded state.

**Comment by allanaaa** [comment]
This is a fair compromise. We do need a bit of styling - wrap the button and user text div in a container so we can add some margin-bottom to that. Otherwise, the paragraph has space underneath but the button doesn't. 

Can the button have the same width whether the setting is on collapse or expand? 

And I would remove the margin-bottom from the fieldset legends; it's creating a lot of unneeded whitespace.

<img width="434" alt="Screenshot 2024-05-06 at 14 06 44" src="https://github.com/omeka-s-modules/FacetedBrowse/assets/28012148/4ae77357-d9a4-4841-8b05-f371b0669384">
<img width="446" alt="Screenshot 2024-05-06 at 14 06 50" src="https://github.com/omeka-s-modules/FacetedBrowse/assets/28012148/4a1c6461-8348-4c86-ba46-27a491753b16">

**Comment by jimsafley** [comment]
I've added a configurable button label. I've also changed the terminology from "user text" to "helper text". The changes require a migration.

**Comment by kimisgold** [comment]
Looks and works great for me.
