### ISSUE TITLE
'Or' for multiple values option

### ISSUE THREAD

**Issue by lguariento** [omeka-s-modules/FacetedBrowse#7]
When choosing the 'Multiple (list).' option for a facet, if I check more than one item in the front-end the query that goes through is an 'AND', not an 'OR'. For example, if a have an authors facet and would like to filter by a couple of authors, I cannot: I get zero results because the query searches for items with 'author1' AND 'author2'. Is it possible to narrow down the table with an 'AND' statement?

**Comment by jimsafley** [comment]
The "Value" facet uses the AND operator because _most_ use cases expect an exclusive search when using facets. The module does not provide an option to choose the OR operator because there's no way to encapsulate logical clauses—combining AND and OR operators would have inconsistent results.

If this isn't a problem, you could make a change to the code. In `asset/js/facet-render/value.js` you could change `[joiner]=and` to `[joiner]=or`. But remember that it will make every "Value" facet type inclusive.

**Comment by lguariento** [comment]
Thank you very much! Actually I'd, instead, expect the 'OR' to be the default. When you are, say, shopping for something, you filter by price. Then you add a new filter for 'colour'. You want to see things with that colour AND that price, not of only that colour. But that's just me :) . I'm happy to have the 'Value' facet always inclusive.

**Comment by lguariento** [comment]
PS: apologies, I realised that what I describe above about the shopping experience is an 'OR' indeed. My scenario then is a specific one, I see it now.
